[package]
name = "pseudo_hexdump"
version = "0.1.0"
edition = "2018"
authors = ["Benjamin Liden <benjamin.c.liden@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
anyhow = "1.0.48"
